-- INSERT INTO question(question_index, description, level) VALUES (1, '만약 타임머신을 탈 수 있다면, 어느 시대를 방문하고 싶나요? 그 이유를 30초 동안 설명해보세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (2, '당신이 가장 좋아하는 계절은 무엇인가요? 그 계절을 좋아하는 이유를 30초 동안 말해보세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (3, '최근에 가장 재미있게 본 영화는 무엇인가요? 왜 재미있었는지 30초 동안 설명해보세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (4, '당신이 가장 좋아하는 음식은 무엇인가요? 이유를 30초 동안 말해보세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (5, '가장 기억에 남는 여행지는 어디인가요? 그 여행이 왜 특별했는지 30초 동안 이야기해주세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (6, '만약 하루 동안 동물이 될 수 있다면, 어떤 동물이 되고 싶나요? 이유를 30초 동안 설명해주세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (7, '아침에 가장 먼저 하는 일은 무엇인가요? 왜 그렇게 시작하나요? 30초 동안 설명해주세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (8, '지금까지 살면서 가장 재미있었던 순간은 언제였나요? 이유를 30초 동안 설명해주세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (9, '당신이 좋아하는 색은 무엇인가요? 그 색을 좋아하는 이유를 30초 동안 말해주세요!', 1);
-- INSERT INTO question(question_index, description, level) VALUES (10, '지금 당장 소원을 하나 빌 수 있다면, 무엇을 빌고 싶나요? 이유를 30초 동안 설명해주세요!', 1);
--
-- INSERT INTO question(question_index, description, level) VALUES (1, '만약 새로운 언어를 하나 배울 수 있다면, 어떤 언어를 배우고 싶나요? 그 이유를 1분 동안 설명해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (2, '당신이 존경하는 인물은 누구인가요? 이유를 1분 동안 설명해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (3, '가장 좋아하는 명언은 무엇인가요? 그 명언이 왜 의미 있는지 1분 동안 이야기해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (4, '자신을 가장 잘 표현할 수 있는 한 단어는 무엇인가요? 이유를 1분 동안 말해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (5, '당신이 좋아하는 책은 무엇인가요? 그 책을 좋아하는 이유를 1분 동안 설명해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (6, '만약 무인도에 가야 한다면, 꼭 가지고 가고 싶은 세 가지는 무엇인가요? 이유를 1분 동안 말해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (7, '좋아하는 취미는 무엇인가요? 왜 그 취미를 즐기게 되었나요? 1분 동안 설명해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (8, '만약 하루 동안 세상을 바꿀 수 있는 힘이 주어진다면, 무엇을 바꾸고 싶나요? 그 이유를 1분 동안 설명해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (9, '당신의 가장 큰 장점은 무엇인가요? 그 장점이 어떤 상황에서 유용하다고 생각하나요? 1분 동안 설명해주세요!', 2);
-- INSERT INTO question(question_index, description, level) VALUES (10, '가장 잊지 못할 생일은 언제였나요? 그 날이 특별했던 이유를 1분 동안 설명해주세요!', 2);
--
-- INSERT INTO question(question_index, description, level) VALUES (1, '지금까지 살면서 가장 큰 도전은 무엇이었나요? 어떻게 극복했나요? 그 경험을 2분 동안 이야기해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (2, '당신이 생각하는 "성공"의 정의는 무엇인가요? 그 정의에 대해 2분 동안 설명해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (3, '만약 세상을 더 나은 곳으로 만들기 위해 할 수 있는 일이 하나 있다면, 무엇을 하겠습니까? 그 이유를 2분 동안 이야기해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (4, '자신이 가장 두려워하는 것은 무엇인가요? 왜 그렇게 생각하나요? 2분 동안 설명해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (5, '당신에게 영감을 주는 사람은 누구인가요? 그 사람에게 어떤 점에서 영감을 받았나요? 2분 동안 설명해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (6, '자신의 성격 중 하나를 바꿀 수 있다면, 어떤 점을 바꾸고 싶나요? 그 이유를 2분 동안 이야기해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (7, '만약 당신이 만든 발명이 인류를 변화시킬 수 있다면, 무엇을 발명하고 싶나요? 이유를 2분 동안 설명해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (8, '자신이 가장 자랑스러웠던 순간은 언제였나요? 그 순간이 특별했던 이유를 2분 동안 설명해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (9, '당신에게 "행복"이란 무엇인가요? 행복을 느낄 때를 2분 동안 이야기해주세요!', 3);
-- INSERT INTO question(question_index, description, level) VALUES (10, '미래에 어떤 모습으로 살고 싶나요? 그 모습을 이루기 위해 지금 무엇을 하고 있나요? 2분 동안 설명해주세요!', 3);


-- # INSERT INTO question(question_index, description)
-- # VALUES (1, '만약 당신이 하루 동안 다른 사람의 삶을 살아볼 수 있다면, 누구의 삶을 살고 싶나요? 그 이유를 1분 동안 설명해보세요!');
-- # INSERT INTO question(question_index, description)
-- # VALUES (2, '만약 당신의 성격이 하나의 날씨라면, 어떤 날씨를 닮았다고 생각하나요? 그 날씨를 닮은 이유를 1분 동안 설명해보세요!');
-- # # INSERT INTO question(question_index, description)
-- # # VALUES (3, '자신의 성격을 동물로 비유한다면, 어떤 동물에 가까운가요? 그 동물을 닮은 이유를 1분 동안 말해보세요!');
-- # # INSERT INTO question(question_index, description)
-- # # VALUES (4, '당신이 가장 좋아하는 계절은 무엇인가요? 그 계절을 좋아하는 이유를 1분 동안 설명해보세요!');
-- # # INSERT INTO question(question_index, description)
-- # # VALUES (5, '자신의 인생을 영화로 만든다면, 어떤 장면이 가장 중요하다고 생각하나요? 그 장면을 선택한 이유를 1분 동안 말해보세요!');
-- # # INSERT INTO question(question_index, description)
-- # # VALUES (6, '당신은 어떤 도형을 닮은 것 같나요? 그 도형을 닮은 이유는 무엇인가요? 1분동안 말해보세요!');
-- # # INSERT INTO question(question_index, description)
-- # # VALUES (7, '자신을 한 단어로 표현한다면, 어떤 단어가 가장 적합하다고 생각하나요? 그 단어를 고른 이유를 1분 동안 말해보세요!');
-- #
-- #
-- # INSERT INTO user(created_at, email, name, oauth_server_id, voice_url, oauth_server, role)
-- # VALUES ('2024-11-14-00:01:04', 'test@example.com', 'test', '1', 'test voice url', 'KAKAO', 'USER');
-- #
-- # INSERT INTO user(created_at, email, name, oauth_server_id, voice_url, oauth_server, role)
-- # VALUES ('2024-11-13-00:01:04', 'test2@example.com', 'test2', '2', 'test voice url', 'KAKAO', 'USER');
-- #
-- # INSERT INTO answer(created_at, user_id, evaluation, question_id)
-- # VALUES ('2024-11-29-00:01:05', '2', 0, 1);
-- #
-- # INSERT INTO answer(created_at, user_id, evaluation, question_id)
-- # VALUES ('2024-11-30-00:01:05', '2', 0, 2);
-- #
-- #
-- # INSERT INTO feedback(user_id, answer_id, before_script)
-- # VALUES (2, 1,
-- #         '음, 만약 하루 동안 다른 사람의 삶을 살 수 있다면... 어, 저는 아마 여행을 많이 다니는 사람의 삶을 살고 싶어요. (1초..) 왜냐면, 음 뭐랄까 저는 여행을 좋아하는데, 사실, 뭐 시간도 잘 안 되고, 그럴 때가 많잖아요? (2초 ..) 그래서 그런 사람처럼 자유롭게 세계를 돌아다니고, 새로운 문화를 경험해보고 싶어요. (1초..) 아, 그리고 그런 사람은 매일매일 새로운 곳에서 음, 그런 신선한 기분을 느낄 수 있잖아요? (2초..) 그래서 그 사람의 삶을 살아보면 그, 뭐랄까, 뭔가 조금 더 자유롭고 신나는 하루를 보낼 수 있을 것 같아서 좋을 것 같아요.');
-- #
-- # INSERT INTO feedback(user_id, answer_id, before_script)
-- # VALUES (2, 2,
-- #         '음 아, 제 성격이 음, 날씨라면 뭐랄까, 비 오는 날씨인 것 같아요. (2초..) 왜냐면, 그 어, 저는 사실 좀 차분하고, 뭐랄까 혼자 있을 때 더 편안함을 느끼는 편이거든요. 아, 그래서 비 오는 날 그, 비가 내리면 뭔가 차분해지고, 생각도 깊어지고, 그러잖아요. (2초..) 아, 근데 또, 때때로 갑자기 막, 뭐랄까 흥분하거나, 기분이 확 변할 때도 있어서, 그런 점에서 뭐, 번개나 천둥처럼 좀 변할 때도 있죠. (1초..) 그, 뭐 그런 감정의 변화를 잘 다룬다고 생각하니까 비와 비슷한 것 같아요.');
-- #
